name: giodonaldson
favicon: null
layout_spectrum: 0.1423
typography_spectrum: 0.74018
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3d1d2'
    - '#ffffff'
    - '#080607'
    - '#7e7661'
    - '#ffba5f'
  brandStrength: 1
  lightness: 0.6346940910443664
  saturation: 1
  rhythmicContrast: 0.2777186583261937
purpose: []
